spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1364pz173b0wz7i.mysql.rds.aliyuncs.com:3306/jzt_hotel?&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: dev_hotel
    password: Luyun2013
  # REDIS (RedisProperties)
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 192.168.0.33
    # Redis服务器连接端口
    port: 6380
    # Redis服务器连接密码（默认为空）
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 1000
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 300
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0

    cluster:
      nodes: 192.168.0.31:6379,192.168.0.33:6379,192.168.1.14:6379

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://192.168.0.34:8761/eureka/,http://192.168.0.32:8761/eureka/

aliyun:
  asc:
    access-key-id: LTAIRyUPzUHWE3aQ
    access-key-secret: 6AItvovD7Pz8cBeFTJdufKE0A89abt
  open-search:
    access-key-id: LTAI8GzwGGb8eAX1
    access-key-secret: q4ENShhuEZZtx90yb7EXczQiKoOpi0
    host: http://opensearch-cn-hangzhou.aliyuncs.com
    app-name: jiu_zhe_hotel_prod
    table-name: jiu_zhe_hotel_prod
  oss:
    access-key-id: LTAI8GzwGGb8eAX1
    access-key-secret: q4ENShhuEZZtx90yb7EXczQiKoOpi0
    end-point: oss-cn-hangzhou.aliyuncs.com
    bucketName:
  mns:
    access-key-id: LTAIRyUPzUHWE3aQ
    access-key-secret: 6AItvovD7Pz8cBeFTJdufKE0A89abt
    end-point: http://1318720335258170.mns.cn-hangzhou.aliyuncs.com/
    queue-name: dev-jzt-hotel-db-log

rabbitmq:
  address: 192.168.0.31:5672
  username: jiuzhe
  password: jiuzhe
  virtualHost: hotel
  exchange:
    default: amq.direct
  queue:
    delay15min: delay.15min

maxreservationday: 38

